config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end
  # config/routes.rb
  devise_for :admins, controllers: {sessions: 'admins/sessions',registrations: 'admins/registrations'}
  devise_for :users, controllers: {sessions: 'users/sessions',registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "homes#about"
  get "top", to: "homes#top", as: "top"

  scope module: :public do
    get 'search', to: 'searches#search', as: 'search'
    get 'users/withdraw', to: 'users#withdraw_confirm', as: 'withdraw_confirm'
    delete 'users/withdraw', to: 'users#destroy', as: 'withdraw'
    resources :users, only: [:edit, :show, :update]do
      resource :follow, only: [:create, :destroy]
      member do
        get :followings   # 自分がフォローしている人一覧
        get :followers    # 自分をフォローしている人一覧
      end
    end

    resources :posts, only: [:new, :index, :show, :create, :destroy] do
      resources :reviews, only: [:index, :new, :create, :destroy]
      resource :post_likes, only: [:create, :destroy]
      resources :comments, only: [:index, :create, :destroy] do
        resource :comment_likes, only: [:create, :destroy]
      end
    end

    resources :notifications, only: [:update]
    resources :categories, only: [:new, :edit, :create, :update, :destroy]
    resources :expenses, only: [:edit, :create, :update, :destroy]
    resources :periods, only: [:index, :show, :edit, :create, :update, :destroy]

    resources :contacts, only: [:new, :create] do
      collection do
          post 'confirm'
          post 'back'
          get 'done'
      end
    end
  end

  namespace :admins do
    root "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :destroy]
  end
end

app/views/admins/_header.html.erb
<header class="fixed-top d-flex justify-content-between header-footer-color" >
  <nav class="navbar navbar-expand-lg navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" 
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "TOP", admins_root_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "会員一覧", admins_users_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "投稿一覧", admins_posts_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "コメント一覧", admins_comments_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "評価一覧", admins_reviews_path, class: "nav-link" %></li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
  <nav class="navbar">
    <div>
      <ul class="navbar-nav d-flex flex-row">
        <h3>管理者</h3>
      </ul>
    </div>
  </nav>
</header>