config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end
  # config/routes.rb
  devise_for :admins, controllers: {sessions: 'admins/sessions',registrations: 'admins/registrations'}
  devise_for :users, controllers: {sessions: 'users/sessions',registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "homes#about"
  get "top", to: "homes#top", as: "top"

  scope module: :public do
    get 'search', to: 'searches#search', as: 'search'
    get 'users/withdraw', to: 'users#withdraw_confirm', as: 'withdraw_confirm'
    delete 'users/withdraw', to: 'users#destroy', as: 'withdraw'
    resources :users, only: [:edit, :show, :update]do
      resource :follow, only: [:create, :destroy]
      member do
        get :followings   # 自分がフォローしている人一覧
        get :followers    # 自分をフォローしている人一覧
      end
    end

    resources :posts, only: [:new, :index, :show, :create, :destroy] do
      resources :reviews, only: [:index, :new, :create, :destroy]
      resource :post_likes, only: [:create, :destroy]
      resources :comments, only: [:index, :create, :destroy] do
        resource :comment_likes, only: [:create, :destroy]
      end
    end

    resources :notifications, only: [:update]
    resources :categories, only: [:new, :edit, :create, :update, :destroy]
    resources :expenses, only: [:edit, :create, :update, :destroy]
    resources :periods, only: [:index, :show, :edit, :create, :update, :destroy]

    resources :contacts, only: [:new, :create] do
      collection do
          post 'confirm'
          post 'back'
          get 'done'
      end
    end
  end

  namespace :admins do
    root "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :destroy]
  end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: [:top]
  
  def about
  end

  def top
    @latest_period = current_user.periods.order(id: :desc).first # 最新登録の期間の取得
    @period = Period.new

    #表示している期間に紐づいているカテゴリだけを取得
    @categories = @latest_period ? current_user.categories.where(period: @latest_period) : []
    @category = Category.new

    @expense = Expense.new
    @categories.each do |category|
      category.expenses.build
    end 
  end
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="py-5 header-footer-color">
  <div class="container position-relative">
    <div class="text-center mt-5">
      <h1 class="display-4" style="color:#e44e2d; font-weight:700;">About</h1>
      <p style="color:#e44e2d; margin-top:-10px;">まねトクについて</p>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <%= image_tag "about-logo.png", class: "img-fluid mb-4", alt: "イメージ画像" %>
    </div>
  </div>
  <div class="row align-items-stretch about-row">
    <div class="col-md-6 p-4" style="background-color:#ff562f; color:white; border-right:3px solid white;">
      <div class="d-flex align-items-center mb-3">
        <h3 class="ml-3 font-weight-bold">ようこそ！</h3>
      </div>
      <p class="text-justify">
        「まねトク」は、毎日の生活における支出の把握や、お金に対する不安を少しでも軽くし、
        より安心して暮らせる環境づくりをサポートする家計管理アプリです。
        シンプルで直感的に操作でき、毎日続けやすい工夫を取り入れています。
      </p>
      <% if user_signed_in? %>
        <div class="mt-4 text-center">
          <%= link_to "はじめよう！", top_path, class: "btn btn-light btn-lg px-4" %>
        </div>
      <% else %>
        <div class="d-flex justify-content-center mt-4">
          <%= link_to "新規登録", new_user_registration_path, class: "btn btn-light btn-lg mx-2 px-4" %>
          <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-light btn-lg mx-2 px-4" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 p-4" style="background-color:#ff562f; color:white;">
      <h3 class="font-weight-bold mb-3">「家計簿 × 節約術 × SNS」</h3>
      <p class="text-justify">
        家計簿機能では、日々の支出を直感的に記録でき、自動計算でお金の流れを分かりやすく可視化します。
        生活費の見直しや無駄遣いの発見に役立ちます。
        さらに、ユーザー同士が節約術を投稿・共有できるコミュニティを用意。
        他の人のアイデアを参考にしたり、自分の工夫をシェアしてフィードバックを受けたりと、
        楽しく学べる環境を提供します。
        「記録」と「学び」を組み合わせることで、無理なく続けられる家計管理を実現します。
      </p>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<%= render "public/header1" %>
<div class="container" style="margin-top:166px;">
<!--カテゴリ登録-->
  <% if @latest_period.present? %>
    <%= link_to new_category_path, class: "btn btn-success fixed-top-right" do %>
      <i class="fa-solid fa-plus fa-2x"></i>
    <% end %>
  <% end %>
  <div class="row justify-content-center mt-4 mb-4">
    <div class="col-md-6">
      <% if @latest_period.nil? %>
        <div class="alert alert-warning text-center p-5 my-4" style="font-size: 1.5rem; background-color: #fff3cd; border-radius: 10px;">
          <strong>まずは「期間」を登録してください！</strong><br>
          登録後に家計簿機能が利用できるようになります
        </div>
      <% end %>

      <%= form_with model: @period, url: periods_path, local: true do |f| %>
        <% if @period.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@period.errors.count, "件のエラー") %>があります：</h4>
            <ul>
              <% @period.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="d-flex justify-content-center">
          <div>
            <%= f.label :start_date, "開始日" %><br>
            <%= f.date_field :start_date, class:"mr-3" %>
          </div>
          <div>
            <%= f.label :end_date, "終了日" %><br>
            <%= f.date_field :end_date, class:"mr-3" %>
          </div>
          <div>
            <%= f.submit "登録", class: "mt-4 btn btn-primary" %>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  
  <!--期間が登録されていない場合はカテゴリ登録ボタンなどを無効化-->
  <% if @latest_period.present? %>

    <!--支出登録のエラーメッセージ-->
    <% if flash[:expense_errors].present? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(flash[:expense_errors].count, "件のエラー") %>があります：</h4>
        <ul>
          <% flash[:expense_errors].each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h5 class="my-4 text-center bg-light">
      <i class="fa-solid fa-bullhorn mr-2 bullhorn-css"></i>カテゴリをクリックして支出一覧を見る
    </h5>

    <div class="row d-flex align-content-center flex-wrap border border-secondary rounded">
      <div class="col-12  p-0 card border-secondary">
        <div class="card-header text-center card-header-color">
          <h3>
            <%= @latest_period.start_date %> ~ <%= @latest_period.end_date %>
            <%= link_to edit_period_path(@latest_period), class:"btn btn-warning" do %>
              <i class="fa-solid fa-pen"></i>
            <% end %>
            <%= link_to period_path(@latest_period), method: :delete,
                        data: {confirm: "本当に削除しますか？"},
                        class:"btn btn-danger" do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </h3>
        </div>
      </div>

        <% @categories.each do |category| %>
        <div class="col-4 card-body">
          <div class="card border-secondary">
            <div class="card-header card-header-color">
              <p><%= link_to category.category_name, period_path(@latest_period), class:"m-0 btn btn-success" %></p>
              残高<%= category.budget - category.expenses.where(period_id: @latest_period.id).sum(:amount) %> 円 <br>
              <%= link_to edit_category_path(category), class:"mt-2 btn btn-warning btn-sm" do %>
                <i class="fa-solid fa-pen"></i>
              <% end %>
              <%= link_to category_path(category), method: :delete,
                          data: {confirm: "本当に削除しますか？"},
                          class:"mt-2 btn btn-danger btn-sm" do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </div>

            
            <%= form_with model: @expense, url: expenses_path, local: true do |f| %>
              

            <div class="card-body">
              <%= f.hidden_field :category_id, value: category.id %>
              <%= f.hidden_field :period_id, value: @latest_period.id %>

                <%= f.label :expense_date, "支出日", class:"font-weight-bold" %>
                <%= f.date_field :expense_date, class:"form-control" %>

                <%= f.label :amount, "支出金額", class:"font-weight-bold" %>
                <%= f.text_field :amount, inputmode: "numeric", pattern: "[0-9]*", class:"form-control" %>

                <%= f.submit "登録", class: "btn btn-primary mt-2" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>